### ISSUE TITLE
Add JSON formatter for CMakePresets.json

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#1]
Add a json formatter for CMakePresets.json
[jq](https://jqlang.github.io/jq/) seems to be a good choice : available for linux, windows and mac

**Comment by folmos-at-orange** [comment]
The pre-commit hook [pretty-format-json](https://github.com/pre-commit/pre-commit-hooks/blob/main/pre_commit_hooks/pretty_format_json.py) seems a good option as well.

The PR KhiopsML/OldKhiops#5 contains a commit that adds pre-commit support plus an action that checks it on push events.

**Comment by bruno-at-orange** [comment]
what about pre-commit hooks to validate actions and workflows:
- check-github-actions - Validate GitHub Actions against the schema provided by SchemaStore
- check-github-workflows - Validate GitHub Workflows against the schema provided by SchemaStore
