### ISSUE TITLE
Segmentation fault in SNB with multiple cores

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops#103]
Bug detecte initialement lors d'un bench d'un bench sur L-TORNADO: E:\utilisateurs\Marc\BenchLargeDataset\bench_large_dataset.py
- tests intensifs sur la gestion des ressources
  - datasets: ['Dilbert', 'Robert', 'Dionis']
  - Max tree number: [0, 10, 100]
  - Max memory: [256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536]
  - Max cores: [1, 2, 4, 8, 16, 32]
- Plante (dans le SNB?) (le rapport de preparation est ok)
	- Dionis	0	4096	16	127.6	(needs extra 1.1 MB)
		khiops ended with return code 15
		Errors in log:
		Line 5: error : Selective Naive Bayes Training : not enough memory to run the task (needs extra 1.1 MB)
		Fatal errors in log:
		Line 6: fatal error : Signal 11 : invalid memory access (segmentation fault)
		Contents of stderr:
		fatal error : Signal 11 : invalid memory access (segmentation fault)
	- faire les tests systématiques avec Dionis

Bug observe tres rarement lors du developpement de Khios V11. Bug non qualifie correctement, potentiellement difficile a reproduire.

Update 2023-12-04
- reproduit sur L-TORNADO avec script bench_large_dataset.py
  - appel de la fonction
    train_classifier("Dionis", "Class", 1, max_memory_mb=4096, max_cores=32, result_file="Bug_Dionis_4096_32.txt")
  - resultats sur la console:
    khiops ended with return code 4294967293
    Errors in log:
    Line 5: error : Selective Naive Bayes Training : not enough memory to run the task (needs extra 1.1 MB)

Urgence: a traiter sous forme de hot-fix des que la version open source est finalisee

**Comment by marcboulle** [comment]
Bug reproduit avec la dernière version 10.5.3-b.0
Plante lors de l'analyse de Dionis, 32 coeurs, 4096 Mb RAM (sur L-TORNADO)
Ne plante pas avec 16 coeurs.

Ci joint un zip contenant un script python (chemins à adapter) reproduisant le problème, avec log et trace dans le répertoire results.

[BugSNBDionis.zip](https://github.com/user-attachments/files/16873659/BugSNBDionis.zip)

**Comment by folmos-at-orange** [comment]
The bug comes from the Parallel framework: When `MasterInitialize` returns `false` the boolean `bProcessEndedCorrectly` in `MasterFinalize` is set to `true`.

This happens only in MPI mode, and not in simulated mode. 

I made a temporary commit (df6f18dd) in the branch for this issue that makes `MasterInitialize` that doesn't initialize anything and returns `false`. This reproduces the bug with any dataset.

I'm transferring this issue to @bruno-at-orange.

**Comment by marcboulle** [comment]
Autre information, après avoir relancé l'outil cette fois en mode debug.
Au bout de 2 à 3 heures, j'ai un assert dans le master:
`Assert failed in file C:\MyApplications\DevGit\khiops\src\Parallel\PLParallelTask\RMParallelResourceManager.cpp line 1671d	dPercentage <= 1 and dPercentage >= 0`
Peut-être un conséquence indirecte problème?
