### ISSUE TITLE
Failure in run-standard-tests (mac parallel) with BugMPIWithErrors

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops#132]
#### Description
After adding test LearningTest\TestKhiops\Standard\BugMPIWithErrors in the git CI/CD:
- Failure in run-standard-tests (macos-latest, macos-clang, parallel, release) with BugMPIWithErrors
- all other test are ok

#### Questions/Ideas
- the build is not the same in the CI/CD as in production for Mac

### Context
- Khiops version: V10.2
- Log file (use `khiops -e log.txt`)
- Scenario file (use `khiops -o scenario._kh`): LearningTest\TestKhiops\Standard\BugMPIWithErrors
- OS description (use `khiops -s`): Mac using git CI/CD
[stderr_error.log](https://github.com/KhiopsML/khiops/files/14038769/stderr_error.log)
[stdout_error.log](https://github.com/KhiopsML/khiops/files/14038770/stdout_error.log)
[return_code_error.log](https://github.com/KhiopsML/khiops/files/14038771/return_code_error.log)

**Comment by folmos-at-orange** [comment]
The error is because the `mpich` installed in the CI comes from the Homebrew package which provides only one version `4.1.2` and this version is bugged.

A solution would be to install another version of mpich in the macos CI machines.
