### ISSUE TITLE
Segmentation fault in Rocky Linux

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#138]
#### Description
The test `TestKhiops/SparseData/ReadSparseFormatCKeysError` fails in release (and not always!) with a segmentation fault

#### Questions/Ideas
After investigation:
- The problem stems from the class `KWValueBlock` not initializing `nValueNumber` and this is an undefined behavior.
  - This class is highly optimized and has a custom generic constructor.

**Comment by marcboulle** [comment]
Solve with merge of pull request
