### ISSUE TITLE
Investigate the impact of pairing `TaskProgression::IsInterruptRequested` with `periodicTestInterruption::IsTestAllowed`

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#141]
#### Description
There are around 250 calls to `TaskProgression::IsInterruptRequested` in the code. As it is not necessary to call it often in critical code we should investigate which of these we should pair with `periodicTestInterruption::IsTestAllowed`. This pairing allows to not call `IsInterruptRequested` too often.

**Comment by marcboulle** [comment]
Un problème critique de performance sur Mac a  été corrigé sur la base TaskProgression::IsInterruptRequested
Cf. issue KWDatabaseTransferTask calls too often TaskProgress::IsInterruptionRequested #139 
La correction rétablit un fonctionnement nominal pour la V10.2

La vérification systématique de l'utilisation de TaskProgression::IsInterruptRequested est potentiellement utile, mais coûteuse à effectuer (temps d'analyse, plus report potentiel des corrections vers la V11)
Elle ne sera a faire que pour la V11

**Comment by folmos-at-orange** [comment]
Just to be precise: The problem was also present in some Linux distributions.

> Un problème critique de performance sur Mac a été corrigé sur la base TaskProgression::IsInterruptRequested Cf. issue KWDatabaseTransferTask calls too often TaskProgress::IsInterruptionRequested #139 La correction rétablit un fonctionnement nominal pour la V10.2
> 
> La vérification systématique de l'utilisation de TaskProgression::IsInterruptRequested est potentiellement utile, mais coûteuse à effectuer (temps d'analyse, plus report potentiel des corrections vers la V11) Elle ne sera a faire que pour la V11

**Comment by marcboulle** [comment]
### Besoins
- amélioration de la gestion des interruptions utilisateurs
  - mieux gérer la dégradation des performances
  - évaluer l'utilisation actuelle de TaskProgression::IsInterruptionRequested et periodicTestInterruption::IsTestAllowed
  - évaluer la possibilité des désactiver la gestion des interruptions utilisateurs en mode batch

### Audit rapide du code
 - note préliminaire
   -  la gestion des interruption utilisateurs est un problème d'ergonomie utilisateur, permettant d'interrompre un traitement en cours, tout en laissant le contexte UI permettant à l'utilisateur de lancer une autre tâche
   - ne doit pas être confondu avec le signal d'interruption pouvant être envoyé par l'OS, qui doit aboutit une une sortie propre du programme (pourra être traite comme une fatal error, dans une autre issue si nécessaire)
- Stats de nombre d'utilisation des méthodes critiques
  - TaskProgression::IsInterruptionRequested: 269
  - TaskProgression::DisplayTaskProgesssion: 85
  - PeriodicTest::IsTestAllowed: 47 (dont dont 17 fois IsTestAllowed(0))
- classe TaskProgression
  - DisplayTaskProgesssion
    - les affichages effectifs sont temporisés avec un timer interne (toutes les 0.3 s)
  - IsInterruptionRequested
    - les test effectifs sont effectués
      - immédiatement si TaskProgressionManager::IsInterruptionResponsive vaut true
      - temporisés avec un timer interne sinon
- classe TaskProgressionManager
  - IsInterruptionResponsive: méthode virtuelle
  - FileTaskProgressionManager: responsive=True (et IsInterruptionRequested renvoie toujours false)
  - UITaskProgression: responsive = false
    - cohérent avec l'interface java
  - PLMPISlaveProgressionManager: IsInterruptionResponsive = true
    - non cohérent avec l'utilisation des probes dans MPI, qui peuvent prendre un peu de temps
- PeriodicTest::IsTestAllowed
  - temporisé par un modulo et un timer
  - utile pour diminuer
    - le nombre de test d'interruption: redondant avec IsInterruptionRequested dans le cas temporisé par un timer
    - le nombre de DisplayTaskProgesssion: redondant avec IsInteDisplayTaskProgesssion toujours temporisé par un timer
    - le nombre de messages construits pour l'appel a DisplayTaskProgesssion

### Proposition d'évolution
- TaskProgressionManager::IsInterruptionResponsive
  - supprimer cette méthode
  - on considère désormais que le test d'interruption n'est jamais "responsive", et on temporise toujours par un timer
- TaskProgression::IsRefreshNecessary
  - nouvelle méthode permettant de temporiser la fabrication des messages pour DisplayTaskProgesssion et le test d'interruption utilisateur
  - utilise un modulo et les timers déja existant dans TaskProgression
  - remplace l'utilisation de PeriodicTest::IsTestAllowed
- PeriodicTest: suppression de la classe et de tous ses usages
- TaskProgression::Set|GetNeverInterrupted
  - GetNeverInterrupted vaut true, la méthode TaskProgression::IsInterruptionRequested renvoie systématiquement false
  - à paramétrer
    - quand on lance les outils en mode batch (cf. UIObject::SetUIMode)
    - à inhiber dans certains cas de test, comme par exemple les CrashTest (cf. GetLearningCrashTestMode)

**Comment by folmos-at-orange** [comment]
- Why not just hide the internal timer completely and make `IsInterruptionRequested` return `false` if the timer hasn't hit the period ? This would allow using `IsInterruptionRequested` without worrying about timers.
  - In this case a new name conveying the "timer" aspect would be better. `IsTimedInterruptionRequested` ?
- Not having a "clean" interruption in batch mode seems a bit too much. I think we should capture `SIGINT` (Ctrl-C) and properly finish as we do in GUI mode 
   - I know at the moment we just make a "dirty exit" but many applications (such as daemons) make some kind of cleaning upon receiving `SIGINT`.

**Comment by marcboulle** [comment]
Clarified after offline discussion: 
- hiden internal timer in classTaskProgression already in specification
- management of SIGINT to have a clean exit is another issue, now created: https://github.com/KhiopsML/khiops/issues/195
