### ISSUE TITLE
Extend the copyright script for python files

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#150]
#### Description
Currently the script `scripts/update_copyright.py` only changes `.cpp` and `.h` files. It should also consider python and shell files

#### Questions/Ideas
- The comment operator depends on the extension:
  - `.py`, `.sh` : `#`
  - `.cmd`, `.bat` : `REM`
  - `.h`, `.cpp`: `//`

**Comment by alexisbondu** [comment]
Uniquement pour les fichiers python.
