### ISSUE TITLE
Port Khiops to macOS

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#16]
- Review CMakeFiles to remove `__UNIX__`  pragmas.
- modify Norm module to build on macOS

**Comment by folmos-at-orange** [comment]
Some things I learnt in my experiments:

- The compiler for XCode is named `AppleClang` in CMake (note that is not the same as `Clang`)
- `AppleClang` does not have the same options, notably there is no "strip" option
-  Maybe the simplest way is to make setup function in `CMakeLists.txt` dedicated to Mac. This way we do not surcharge of  `if` statements the current "unix" setup function.

**Comment by folmos-at-orange** [comment]
Related:  `find_mpi` does not work with `Clang` so maybe it is similar for `AppleClang`. Maybe you'll have to bring back your workaround.

**Comment by bruno-at-orange** [comment]
> Some things I learnt in my experiments:
> 
>     * The compiler for XCode is named `AppleClang` in CMake (note that is not the same as `Clang`)
> 
>     * `AppleClang` does not have the same options, notably there is no "strip" option
> 
>     * Maybe the simplest way is to make setup function in `CMakeLists.txt` dedicated to Mac. This way we do not surcharge of  `if` statements the current "unix" setup function.

The tests made with Alexis didn't use XCode but vscode. I'm not sure but I think that clang was already on the system...   And it compiles fine with the current CMakeFiles

**Comment by bruno-at-orange** [comment]
Comments on the branch [16-porting-to-macos](https://github.com/KhiopsML/khiops/tree/16-porting-to-macos):

- The build is OK except for **gtest** where `regex.h` is missing (https://github.com/KhiopsML/khiops/actions/runs/5376228304/jobs/9753105311).
- For the compiler options, the only problem was the hardening flags mandatory for debian. I have excluded them for macOS. 
- There are a lot of warnings while building.
- The build was not parallelized without the `--parallel `option on the build preset (it should be parallel by default but it is not the case on macos)

I propose to merge this branch and to open 2 issues (one for the warnings, one for google test).  It will allow us to work on other features (conda build...) and to invite Alexis on github.
