### ISSUE TITLE
Windows installer does not work properly on re-installation

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#167]
#### Description
When installing Khiops Desktop on a machine having already an installation the process erases the files it creates, leaving at the end of the process only the shortcuts pointing to non-existent files.

#### Questions/Ideas
- Hypotheses:
 - A data race between the execution of the uninstaller and the installer
 - An aggressive antivirus that erases suspicious files

### Context
- Khiops version: 10.2.0
- Env Windows "YourDev"

**Comment by folmos-at-orange** [comment]
~~Closed as duplicate #168.~~

**Comment by folmos-at-orange** [comment]
I could not reproduce this on:
- Windows 10 machine (home)
- Windows 10 machine (professional)

Installed and reinstalled.

**Comment by marcboulle** [comment]
After reboot of my machine, cannot reproduce the problem
Maybe my machine is unstable
Decision: keep the trouble shooting info on khiops.org
Close the issue as it cannot be reproduced
