### ISSUE TITLE
Khiops desktop does not work on some machine under Windows 11

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops#168]
#### Description
Après une installation de Khiops desktop sans problème sur Windows 11, rien ne se passe quand on clique sur l'icone de lancement de Khiops:
- l'outil ne se lance pas
- aucune information utilisateur

#### Questions/Ideas
- tests additionnels, sans amélioration
  - réinstallation
  - réinstallation dans un répertoire utilisateur c:\users\...
  - réinstallation d'un Java récent provenant du site Oracle
  - lancement sans MPI (en modifiant a la main le khiops.cmd)
  - installation avec l'ancien installeur 10.1.1 provenant de l'ancien site khiops.com
- ce qui marche
  - en lancant "khiops -h" depuis un "shell khiops", cela marche: donc l'exe Khiops est ok
  - en inspectant le fichier log.txt du répertoire lastrun, on a
~~~
 error : Java : Unable to load jvm.dll (Le module spécifié est introuvable.), install Java JRE or check the PATH variable
 error : Unable to load GUI, use -b and -i flags to launch khiops in batch mode (khiops -h for help)
~~~
- inspection additionnelle
  -  java est correctement installé, avec la jvm.dll dans le bon chemin
  - en mettant de la trace à la main dans le khiops.cmd:
    - les scripts khiops_env.cmd et khiops.cmd identifient correctement l'installation de java, et la mettent correctement dans le path
  - cela semble donc l'exe lui-même qui n'arrivent pas à charger la dll: à investiguer
- ajout de trace en C++
  - UIObject::GetJNIEnv
    - détection correcte du path via FileService::GetPathDirectoryList()
    - détection correction du chemin d'accès à la jvm.dll via sJvmLibraryPathName
  - LoadSharedLibrary
    - paramètres corrects
    - transformation correcte en format wide char via MultiByteToWideChar 
      (affiche avec `std::wcout << "String " << wString << endl;`)
  - mais l'appel de la fonction Windows LoadLibrary retourne NULL!
    - investigation en cours
- deux problèmes à corriger: 
  - corriger le bug
  - émettre des infos utilisateur en cas de problème: il suffit d'ajouter une ligne comme la ligne suivante en fin des scripts khiops.cmd et khiops_coclustering.cmd (ou mieux: tester si le code retour est différent de 0 et de 2)
~~~
:END
if "%errorlevel%".==1. start "KHIOPS CONFIG PROBLEM" echo ERROR return code %errorlevel%: see "%KHIOPS_LAST_RUN_DIR%\log.txt" for more info
endlocal
~~~

A tester: tenter de reproduire sur un autre PC sous Windows 11

 
### Context
- Khiops version: 10.2.0
- OS description: Windows 11

**Comment by folmos-at-orange** [comment]
I could not reproduce this on:
- Windows 10 machine (home)
- Windows 10 machine (e-buro)

Installed and reinstalled.

**Comment by folmos-at-orange** [comment]
@stephanebouget tested in Win11. It worked.

However he has an antivirus alert.

**Comment by marcboulle** [comment]
Les test précédents montrent que l'erreur est localisé autour de l'appel de la fonction système Windows LoadLibrary, qui échoue en renvoyant NULL bien que ses paramètre soient corrects.

L'API Windows étant riche, les essais systématiques suivants ont été effectués, malheureusement tous infructueux.
Ils marchent tous sur ma machine, mais aucun ne marche sur la machine Windows 11
Le paramètre initial sLibraryPath a été découpé en sDllDirectory et sDllName, et les variantes wide char ou Ansi char ont été testées, ainsi que la fonction LoadLibraryEx qui permet de spécifier des options avancées.
- LoadLibrary(sLibraryPath )
- LoadLibrary(sDllName)
- SetDllDirectoryA(sLibraryPath), puis LoadLibraryA(sDllName)
- SetDllDirectory(sLibraryPath), puis LoadLibraryEx(sDllName, NULL, LOAD_IGNORE_CODE_AUTHZ_LEVEL)
- SetDllDirectory(sLibraryPath), puis LoadLibraryEx(sDllName, NULL, option), avec toutes les options possibles de LoadLibraryEx

**Comment by marcboulle** [comment]
J'ai finalement trouvé le bug avec du googling, en tombant sur le site https://stackoverflow.com/questions/36978967/load-dll-library-error-126-trying-to-create-a-jvm
En particulier, les dll vcruntime140.dll and msvcp140.dll doivent être présentes dans le répertoire C:\Windows\sytem32

Il faut avoir les packages redistribuables Visual C++ installés:
- google "microsoft visual c++ 2015 to 2022 redistributable package (x64) download"
- site de telechargement Mircosoft: https://learn.microsoft.com/fr-fr/cpp/windows/latest-supported-vc-redist?view=msvc-170
- télécharger le package redistribuable X64
- après installation, cela marche correctement

Solution
- soit les linker statiquement avec l'exe, comme cela était fait dans une ancienne version
- soit les installer avec l'installeur de Khiops

**Comment by folmos-at-orange** [comment]
Our compilation does effectively link statically the MS C++ library (Flags `/MT` or `MTd`). After investigating a bit I found that it is `jvm.dll` that loads `msvcp140.dll` (see below for the `dumpbin` output).

It's also apparent that the `msvcp140.dll` is not included in windows 11 by default. In windows 10 I uninstalled all "Visual C++ redistributable ..." packages and `msvcp140.dll` is still there.

Decision: 
- bundle the visual c++ redist in the khiops installer.
- add the info code proposed above to the launcher script

---
dumpbin output
```
C:\Program Files\Microsoft Visual Studio\2022\Community>dumpbin /dependents "\Program Files\khiops\bin\MODL.exe"
Microsoft (R) COFF/PE Dumper Version 14.36.32537.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file \Program Files\khiops\bin\MODL.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    msmpi.dll
    KERNEL32.dll
    ADVAPI32.dll
    WINMM.dll
    IPHLPAPI.DLL

  Summary

        A000 .data
       2A000 .pdata
       A3000 .rdata
       10000 .reloc
        1000 .rsrc
      2F8000 .text
        1000 _RDATA

C:\Program Files\Microsoft Visual Studio\2022\Community>dumpbin /dependents "C:\Program Files\Java\jdk-1.8\jre\bin\server\jvm.dll"
Microsoft (R) COFF/PE Dumper Version 14.36.32537.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Program Files\Java\jdk-1.8\jre\bin\server\jvm.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    USER32.dll
    ADVAPI32.dll
    WSOCK32.dll
    WINMM.dll
    VERSION.dll
    PSAPI.DLL
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll

  Summary

       86000 .data
       46000 .pdata
      1DA000 .rdata
       2F000 .reloc
        1000 .rsrc
      5D0000 .text
```

**Comment by marcboulle** [comment]
Concernant les alertes antivirus sur la machine de Stéphane:
- quelle est la nature et la fréquence des alertes?
- à vérifier: est-ce que la signature des exe et dll de Khiops pourraient apporter une solution
  - je viens de vérifier que les exe et dll de la plupart outils sont signés: java, Git, mpiexec, FireFox, TextPad, Winmerge...
  - quelques exceptions: 7-zip, TeXnicCenter
- sinon, y a-t-il une solution?
- sinon, ajouter un 'trouble shooting' sur le site khiops.org?

**Comment by stephanebouget** [comment]
J'ai testé un uninstall/reinstall et je n'ai pas eu le message.
j'ai aussi essayé avec un second compte sur la même machine et pas de message,
ce n'est donc à priori pas systématique.

**Comment by folmos-at-orange** [comment]
Update: The `vcruntime140.dll` library is bundled with JRE. So the solution is to add `%JAVA_HOME%\bin` to the path in the Khiops startup script.
