### ISSUE TITLE
Khiops installation fails on Windows with eburo config

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops#202]
#### Description
Echec de l'installation de Khiops sur une machine eburo nouvelle , pour Khiops desktop et via conda (hier, chez Carine)
- via conda: message d'erreur non encore collectés
- via installation Khiops desktop: message de l'installeur "Could not install Java runtime (version ...): Khiops will run only in batch mode. Try installing Java JRE directly before installing to Khiops."

#### Eléments de contexte
- la machine venait d'être configurée par la DSI (pas de java ni de python installé)
- les procédures spécifiques d'installation pour les machine eburo sont non documentées et donc inaccessibles à ceux qui ne les connaissent pas
  - même l'installation d'un outil comme winmerge a échoué
- problème non encore entièrement qualifié, et encore moins résolu
  - pour conda
    - message d'erreur à collecter
    - mais la configuration des proxy , nécessaire, n'a pas été mise en place
  - pour Khiops desktop, tentative en copiant l'installeur dans "My program files", le lançant en tant qu'administrateur, et demandant une installation dans "My program files"
    - il se peut qu'il y ait un processus DSI spécifique pour demander les droits administrateurs (je ne le connais pas)
    - Khiops s'est installé, mais n'est utilisable qu'en mode batch
- la stagiaire de Nicolas a réussi une installation sur eburo il y a deux semaine (avec un simple download puis installation en tant qu'administrateur)
- la semaine dernier, Bruno a été contacté par un utilisateur Orange, pour un problème semble-t-il similaire (verbatim: "la DSI ne permet plus d'installer java"), mais l'utilisateur semble avoir abandonné
- est-ce un problème récent de changement des configs des machines de la DSI?

Nouveau
- Nicolas vient de demander une nouvelle machine eburo en prêt à la DSI (machine sans java ni MPI), et on on a réussi une installation de Khiops desktop très simplement
- il y a donc visiblement plusieurs type de config eburo: à investiguer
  - Carine a une tour, et la machine en prêt est un portable?

#### Questions/Ideas
Le problème n'est pas nécessairement de notre fait, mais il doit être résolu de toutes façon.

A faire
- qualifier le problème chez CH et le résoudre
- si nécessaire, faire un patch des packages et installeurs
- améliorer la prise en charge des utilisateurs sur le site khiops.org
  - améliorer l'onglet "Installation" du site, en collaboration avec CH, pour permettre aux utilisateurs d'être autonomes dans la résolution des problèmes
  - donner des informations spécifiques Orange pour les utilisateurs internes 
    - problème technique à résoudre: donner ces infos "internes" sur un site externe
    - a minima, message "littéraire" de type "For Orange users, see intranet dedicated web pages"
  - permettre aux utilisateurs de nous contacter facilement
  - mettre en place une procédure réactive de réponse à ces contacts utilisateurs
- améliorer nos procédures de tests avant release, pour à l'avenir détecter ce type de problème a priori
- contacter la DSI pour demander aide, support, voire ajout de Khiops au "Centre logiciel"

### Context
- Khiops version: 10.2.0
- OS: Windows eburo

**Comment by bruno-at-orange** [comment]
- Finalement Carine a installer Khiops sans problème : apparemment, la machine n'avait pas fini le cryptage du disque. Après avoir attendu la fin de cette opération, l'installation s'est déroulée sans problème (c'est quand mêmem trèèèès long.
- J'ai contacté l'autre utilisatrice qui n'arrivait pas non plus a faire l'installation et cetet foi sça a fonctionné

**Comment by marcboulle** [comment]
A transférer vers la tribu user first
