### ISSUE TITLE
Driver loading causes unwanted warning in jupyter

### ISSUE THREAD

**Issue by sgouache** [KhiopsML/khiops#207]
#### Description
When khiops has a cloud storage driver installed, it dumps a message to stdout.
This message is considered as abnormal by khiops-python - normally all messages are set to the logs - and result in an ugly error when run in a jupyter notebook.

#### Questions/Ideas
- why not reroute this message to traces, debug ?
- how about suppressing it entirely, it would be a 5s fix
- fixing it in khiops-python is feasible but would imply making an exception just for this case

### Context
- Khiops 10.2.0
- khiops-python 10.2.0.0

![image](https://github.com/KhiopsML/khiops/assets/63242745/2503707b-c2e0-4b4d-b691-e55e20adb777)

**Comment by folmos-at-orange** [comment]
The warning is shown because any `stdout` content is considered spurious and `khiops-python` warns about that. 

Could the message be redirected to the log ?

**Comment by bruno-at-orange** [comment]
In the dev branch  this message is not in the stdout anymore. It appears only when we launch Khiops with the new flag "-s". I will try to add this feature in the next release 10.3

**Comment by marcboulle** [comment]
Pourquoi ne pas ajouter une info dans le log utilisateur, uniquement au chargement de l'outil?
Permettrait d'informer l'utilisateur que les fichier S3 sont utilisable par exemple (un peu de bug)
A ne faire éventuellement que pour la V11: nouvelle issue à créer.

**Comment by bruno-at-orange** [comment]
close in #229
