### ISSUE TITLE
Perimeter of the version 10.3.0

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#211]
We plan to release a 10.3.0 version in few weeks. What I plan to add in this version:
- the switch from MPICH to OpenMPI: we hope that will fix bug on debian and conda. Better integration of Khiops on K8s
- Remove the driver information in the stdout #207 
- Add the possibility to activate easily the file server process on a single host in order to run Learning Test with a file server.

Other ideas or needs ?

**Comment by marcboulle** [comment]
Pour discussion

Avant la 10.3.0, finaliser la version 10.2 open source.
- correction des bugs résiduels
- corriger et diffuser les packages pour les plateformes manquantes, à définir précisément: Rocky8, Debian 11 et 12, desktop...
- signature des packages et repos
- site
  - référencer KNI
  - possibilité de contact utilisateur, avec processus de gestion des messages utilisateurs
  - corrections mineurs sur les pages Installation et Tutorial
- page plazza pour aide spécifique aux utilisateurs Orange?
- ...

Pour la 10.3.0, ou autres numéros à définir, et éventuellement plusieurs lots:
- Khiops visualization et covisualization, selon disponibilité des dernières versions
- amélioration des la gestion des samples
  - via desktop, Windows et Linux
  - via API pykhiops à améliorer et corriger
  - via le site, qui utilise actuellement directement des url
- pykhiops
  - amélioration de la robustesse et des messages d'erreur pour les problème d'installation
    - notamment, si installation par pip, sans installation desktop, ou après désinstallation desktop
      (se mettre à la place d'utilisateurs ni compétents, expérimentés, motivés)
  - liens 1-1
- lancement de la visu depuis des notebook?
- ...

**Comment by folmos-at-orange** [comment]
> Pour discussion
> 
> Avant la 10.3.0, finaliser la version 10.2 open source.
> 
> * correction des bugs résiduels
> * corriger et diffuser les packages pour les plateformes manquantes, à définir précisément: Rocky8, Debian 11 et 12, desktop...

- Rocky 8 support is OK in the next `khiops-python` release : https://github.com/KhiopsML/khiops-python/blob/dev/CHANGELOG.md
- Debian 11 is blocked in the foreseeable future unless we provide our own mpich package.
- Debian 12 is blocked by #163 

> * signature des packages et repos
> * site
>   
>   * référencer KNI
>   * possibilité de contact utilisateur, avec processus de gestion des messages utilisateurs
>   * corrections mineurs sur les pages Installation et Tutorial
> * page plazza pour aide spécifique aux utilisateurs Orange?
> * ...
> 
> Pour la 10.3.0, ou autres numéros à définir, et éventuellement plusieurs lots:
> 
> * Khiops visualization et covisualization, selon disponibilité des dernières versions
> * amélioration des la gestion des samples
>   
>   * via desktop, Windows et Linux
>   * via API pykhiops à améliorer et corriger
>   * via le site, qui utilise actuellement directement des url
> * pykhiops
>   
>   * amélioration de la robustesse et des messages d'erreur pour les problème d'installation
>     
>     * notamment, si installation par pip, sans installation desktop, ou après désinstallation desktop
>       (se mettre à la place d'utilisateurs ni compétents, expérimentés, motivés)
>   * liens 1-1

These two last issues are solved in the next `khiops-python` version: https://github.com/KhiopsML/khiops-python/blob/dev/CHANGELOG.md

> * lancement de la visu depuis des notebook?

I do not think this last issue is blocking the `10.2.x` releases

> * ...

**Comment by marcboulle** [comment]
#### Autres fonctionnalités à diffuser avant la V11
Après fiabilisation, CI/CD, documentation:
- multi-machine, via les serveurs de fichiers
- multi-cloud, via les drivers de fichiers (clouds et OS à définir)

Attention, les nouveaux développements des versions 10.2.x ou 10.3.x vont exiger une double maintenance entre les branches V10.2.x et V11: ne pas trop charger la barque, d'autant que la V11 est presque prête pour une alpha diffusable en interne.

A préciser:
- possibilité d'avoir des versions release, pre-release (cachée) ou non, voir des versions internes uniquement à fins de tests
- politique de numérotation des versions majeures, mineures, patch
- politique de choix des versions diffusées (on attend plusieurs corrections de bug avant de faire un patch, sauf si bug bloquant)
- synchronisation de la diffusion des versions de Khiops core avec celles de pykhiops et la diffusion via le site khiops.org

#### Autres priorités

Finalisation du CI/CD et passage de tous les processus et données "historiques" vers github, gitlab,...

Diffusion de la V11 en alpha en interne dès que possible

**Comment by marcboulle** [comment]
cf. Prepare new minor releases before V11 https://github.com/KhiopsML/pilotage/issues/5
