### ISSUE TITLE
Change exit status of Khiops

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#216]
The exit status of MODL and MODL_coclustering  is as follows:
- return 0 when there is no failure
- return 1 when there is a fatal error
- return 2  when there is a user warning/error

This is a problem with open MPI because it adds the following lines when the return code is not 0:

> 
> --------------------------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> 
>   Process name: [[34210,1],0]
>   Exit code:    2
> --------------------------------------------------------------------------

We have to remove the exit code 2, to keep these lines only in case of fatal error.

**Comment by marcboulle** [comment]
Vue en concertation avec Felipe, Vladimir (pykhiops) et Stéphane (automl).
Ok pour se remaner à un comportement plus simple: retourne 0 si OK et 1 si erreur fatale
Pas d'impact hors khiops core

Correction pragmatique pour la V10.2: juste renvoyer 0 au lieu de 2

Correction plus "propre" dans la V11: nettoyage du code pour se ramener au nouveau comportement, en supprimant les contournements un peu "tricky" qui avaient été mis en place pour gérer de façon spécifique le code retour 2.

**Comment by bruno-at-orange** [comment]
Correction pragmatique pour la V10.2: juste renvoyer 0 au lieu de 2
fait dans #203

**Comment by bruno-at-orange** [comment]
close with #252
