### ISSUE TITLE
Document Khiops testing procedure on Dockerized Linuxes and apply it to Rocky (and other supported OSes)

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops#220]
#### Description
Khiops desktop is currently tested manually as documented in the https://github.com/KhiopsML/khiops/wiki/Release-Process#linux document.

In order to be able to test all supported distributions from a single host system, a Docker-based procedure is possible. The challenge lies in displaying the Khiops desktop native GUI windows from the Docker containers.

#### Questions/Ideas
- The Docker-based Khiops desktop testing procedure needs to be documented.
- Then, the procedure needs to be applied to Rocky linux, for a start.

**Comment by popescu-v** [comment]
Docker-based Khiops desktop testing setup documented on: https://github.com/KhiopsML/khiops/wiki/Release-Process#checklist-1 (second bullet).

**Comment by alexisbondu** [comment]
OK
