### ISSUE TITLE
Rockylinux packages issue with java version and posint script

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#221]
There are two issues with rpm packages:
- the post-installation script is run before the dependencies installation (at least on local install). Consequently, java is not found and JAVA_HOME is not set in the `khiops-env ` script and so the GUI is not launched.
- the jdk used to build the jars is **java-17-openjdk-devel** whereas the default java is 1.8. We have the message:
> Exception in thread "main" java.lang.UnsupportedClassVersionError: normGUI/engine/GUIObject has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by bruno-at-orange** [comment]
For the second issue, I suggest to use the default jdk on the docker (java-devel). It is against our pinning policy but, in the post-installation script, we run `readlink -f /usr/bin/java` to get the path of JAVA_HOME. /usr/bin/java redirects always to the jre 8 even if java 17 is installed.

**Comment by bruno-at-orange** [comment]
for the first issue, I suggest to remove the post-installation script. The khiops-env would look like 
```bash
# Set java environment for GUI if Khiops GUI is installed
if [[ -f "/usr/share/khiops/khiops.jar"  ]]; then
   if [-n "$JAVA_HOME ]; then JAVA_HOME=$(readlink -f /usr/bin/java); fi
   KHIOPS_CLASSPATH=/usr/share/khiops/norm.jar:/usr/share/khiops/khiops.jar
   KHIOPS_JAVA_PATH=$(find -L "$JAVA_HOME" -name libjvm.so | xargs dirname)
fi
```

**Comment by popescu-v** [comment]
> for the first issue, I suggest to remove the post-installation script. The khiops-env would look like
> 
> ```shell
> # Set java environment for GUI if Khiops GUI is installed
> if [[ -f "/usr/share/khiops/khiops.jar"  ]]; then
>    if [-n "$JAVA_HOME ]; then JAVA_HOME=$(readlink -f /usr/bin/java); fi
>    KHIOPS_CLASSPATH=/usr/share/khiops/norm.jar:/usr/share/khiops/khiops.jar
>    KHIOPS_JAVA_PATH=$(find -L "$JAVA_HOME" -name libjvm.so | xargs dirname)
> fi
> ```

OK, but in this case also remove the Debian postinst script?

**Comment by popescu-v** [comment]
> For the second issue, I suggest to use the default jdk on the docker (java-devel). It is against our pinning policy but, in the post-installation script, we run `readlink -f /usr/bin/java` to get the path of JAVA_HOME. /usr/bin/java redirects always to the jre 8 even if java 17 is installed.

Perhaps we can also force /usr/bin/java to point to the java 17:
```sh
alternatives --set java /usr/lib/jvm/java-17-openjdk-17.0.10.0.7-2.el8.x86_64/bin/java
```
?
