### ISSUE TITLE
Sign macOS binaries in CI

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#224]
#### Description
The PR #214 added the `osx-arm64` build for the conda khiops executables. Since in `osx-arm64` non signed binaries add unwanted popups we should sign them.

#### Questions/Ideas
- Add the macOS certificate to the secrets
- Change the signature code in `packaging/conda/build.sh`so it is signed only on request
  - Currently it is triggered by setting a specific environment variables.

**Comment by folmos-at-orange** [comment]
After discussion in weekly:
- Put secrets in vault immediatly
- Put the signature flag afterwards solving this issue.

**Comment by folmos-at-orange** [comment]
After thinking about it even just putting the secrets in the vault needs a change in the code. So I think I'll leave all this work for later.

**Comment by lucaurelien** [comment]
Done in PR #330 and #332
