### ISSUE TITLE
Eliminate LearningTest directory naming requirement from kht_test

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#233]
#### Description
Currently, the `kht_test.py` script fails if the sources/references directory isn't named `LearningTest`. This is very inconvenient when unpacking the `LearningTest` references locally one may have different versions.

#### Questions/Ideas
- Instead of using the `LearningTest` directory anchor use a empty file `.LEARNING_TEST_ROOT`

**Comment by alexisbondu** [comment]
Une première version réalisée en P1 avec la possibilité d'avoir un suffixe. Si il y a des usages bloqués à cause de cela, nous irons plus loin dans un second temps.
