### ISSUE TITLE
Entries containing only empty sparse blocks are not supported

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops#235]
#### Description
Currently, entries that only have one column which is a sparse block which has all variables as missing (undefined) are not processed and predictions are not computed.

Namely, entries which only contain one single sparse block for which all values are missing are not being predicted targets for.

These entries are specified through dictionaries which have all variables in a single block (which is the sparse block).

### Context
- Khiops version: 10.2.0

**Comment by marcboulle** [comment]
Je n'arrive pas à reproduire le problème:
- dictionnaire comportant un bloc sparse et une variable de classe
- fichier utilisé pour le déploiement de modèle sans la colonne de la variable de classe (toléré, car variable non utilisé), avec des valeur manquante pour le bloc en entrée

Vladimir a envoyé un jeu de test permettant de reproduire le problème.
La différence est que dans son jeu de test,n aucune variable en entrée n'est informative, et que le modèle est calculé sans utilisé aucune variable du fichier.

Il s'agit d'un effet de bord "multiple":
- un seul bloc (ou une seule variable) en entrée en plus de la variable de classe
- fichier à déployer avec une seule colonne (sans la colonne de la variable de classe)
- valeurs manquantes dans cette colonne
- aucune variable informative, et donc bloc en entrée non utilisée pour le calcul des scores
