### ISSUE TITLE
Inverse order of parameters of kht_apply

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#236]
#### Description
Currently, the `kht_apply` script call is of the form 

    kht_apply <RESULTS_DIR> <COMMAND>

To be coherent with standard command line tools (eg. `git`, `conda`, `pip` `brew`, etc) it should be the inverse

    kht_apply <COMMAND> <RESULTS_DIR>

**Comment by alexisbondu** [comment]
à soumettre au vote la prochaine fois ;) quelle diffusion pour ces scripts ?

**Comment by alexisbondu** [comment]
Décision (par vote) de ne pas inverser l'ordre des paramètres car ces scripts sont diffusés en interne uniquement.
