### ISSUE TITLE
Do not use GLOB to add source files with CMake

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#24]
This is not recommended by the CMake project: See the note in https://cmake.org/cmake/help/latest/command/file.html#filesystem

**Comment by bruno-at-orange** [comment]
I suggest to wait a stable source tree before enabling this. GLOB is not recommended but it is very useful during big refactoring.

**Comment by folmos-at-orange** [comment]
Ok. I thought we had already all the CPP sources in the tree, why it helps in a refactoring? or why it is risky removing the GLOBs?

I'll have the patch ready in any case.

**Comment by bruno-at-orange** [comment]
Marc is coming soon with few versions and plenty new files

**Comment by folmos-at-orange** [comment]
From the [CMake documentation](https://cmake.org/cmake/help/latest/command/file.html#filesystem), this is the reason they do not recommend using GLOBs for source files

> Note We do not recommend using GLOB to collect a list of source files from your source tree. If no CMakeLists.txt file changes when a source is added or removed then the generated build system cannot know when to ask CMake to regenerate. The `CONFIGURE_DEPENDS` flag may not work reliably on all generators, or if a new generator is added in the future that cannot support it, projects using it will be stuck. Even if `CONFIGURE_DEPENDS` works reliably, there is still a cost to perform the check on every rebuild.

**Comment by folmos-at-orange** [comment]
Decision:
- We'll keep globs whenever possible. Is more practical
- Most of the time removing the `build` directory solves any issue.
