### ISSUE TITLE
Create dictionary file from data table doesn't work well with quoting

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#247]
#### Description
When feeding a quoted file that contains the separator, the create dictionary file feature doesn't parse well the table.

For example with:
```csv
User_ID,Age,Clothing ID,Date,New,Title,Recommended IND,Positive Feedback average
60B2Xk_3Fw,33,767,2019-03-22,True,Awesome,1,0.0
J94geVHf_-,34,1080,2019-03-23,False,Very lovely,1,4.3
jsPsQUdVAL,60,1077,2019-03-24,True,"Some major design flaws, shame!",0,0.0
tSSBwAcIvw,50,1049,2019-03-25,False,My favorite buy!,1,0.5
-I-UlX4n-B,47,847,2019-03-26,False,Flattering shirt,1,6.0
4TQsd3FX7i,49,1080,2019-03-27,True,Not for the very petite,0,4.0
7w824zHOgN,39,858,2019-03-28,True,Cagrcoal shimmer fun,1,3.6
Cm6fu01r99,39,858,2019-03-29,True,"Shimmer, surprisingly goes with lots",1,4.0
zbbZRgbqar,24,1077,2019-03-30,False,Flattering,1,0.0
WfkfYVhQFy,34,1077,2019-03-31,False,Such a fun dress!,1,0.0
```

It creates the dictionary:
```C++
Dictionary	test
{
	Categorical	User_ID		;
	Numerical	Age		;
	Numerical	`Clothing ID`		;
	Date	Date		;
	Categorical	New		;
	Categorical	Title		;
	Categorical	`Recommended IND`		;
	Numerical	`Positive Feedback average`		;
};
```

The `Recommended IND` field is parsed as `Categorical` because some of the records of `Title` have quotes and are "leaked" to the `Recommended IND` field. Note that the deployment with the same dictionary parses well the fields and it doesnt' "leak" the fields with `,`.

**Comment by marcboulle** [comment]
Toute variable booléenne (variable numérique ne contenant que des 'O' ou des '1') est reconnue comme variable catégorielle et non numérique (évolution depuis la version V10.0.1). Ce n'est donc pas un bug.

Test additionnels effectués pour vérifier le bon fonctionnement:
- données initiales: le dictionnaire indiqué est bien reconstruit
- données en remplaçant les ',' par des ';' dans les champs entre double-quotes, et en supprimant les double-quotes: idem
- donnée en remplaçant une des valeurs '1' par '2' dans la colonne `Recommended IND`: cette fois, la variable est détectée comme numérique

**Comment by folmos-at-orange** [comment]
> Toute variable booléenne (variable numérique ne contenant que des 'O' ou des '1') est reconnue comme variable catégorielle et non numérique (évolution depuis la version V10.0.1)

Ok

Ce n'est donc pas un bug.
> 
> Test additionnels effectués pour vérifier le bon fonctionnement:
> 
> * données initiales: le dictionnaire indiqué est bien reconstruit
> * données en remplaçant les ',' par des ';' dans les champs entre double-quotes, et en supprimant les double-quotes: idem
> * donnée en remplaçant une des valeurs '1' par '2' dans la colonne `Recommended IND`: cette fois, la variable est détectée comme numérique
