### ISSUE TITLE
Cherry pick from V10.5 of Eliminate LearningTest directory naming requirement from kht_test

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops#249]
Report de l'amélioration de la PR #248
"Eliminate LearningTest directory naming requirement from kht_test"

**Comment by marcboulle** [comment]
La nouvelle version de LearningTestTool n'est pas encore mergée dans la branche dev-v10
En attente de la PR liée à l'issue Switch to OpenMPI for Linux packages #203
 
Il faudra:
- reprendre la nouvelle version de LearningTestTool issue de la PR https://github.com/KhiopsML/khiops/pull/248 mergée dans dev
- intégrer les évolution spécifiques développées pour OpenMPI (cf. issue #203)
- merger dans dev-v10, puis reporter les évolution spécifique OpenMPI dans dev

**Comment by bruno-at-orange** [comment]
close with commit 89c9975
