### ISSUE TITLE
Remove license manager code

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#25]
This code is obsolete since Khiops 10.1, we should remove it.

**Comment by bruno-at-orange** [comment]
Marc will soon update the sources and the license code will diapear

**Comment by folmos-at-orange** [comment]
To be closed when the branch `dev-v11` is merged to `dev`

**Comment by marcboulle** [comment]
Done in dev-v11 branch, to be merged with dev in close future
