### ISSUE TITLE
Drivers location for conda environment

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#273]
On Linux the khiops drivers are located on `/usr/lib`. It is hardcoded in Khiops, it looks for drivers in this directory only.
We have to discuss how to manage this on conda environments.

**Comment by bruno-at-orange** [comment]
A proposal:
A new environment variable in khiops_env: **KHIOPS_DRIVERS_LOCATION**. If it is set, Khiops will use it to looking for the drivers. If not, Khiops will looking for the drivers in the default location (/usr/lib in windows).
On conda, KHIOPS_DRIVERS_LOCATION is set to `$CONDA_PREFIX/lib`

**Comment by popescu-v** [comment]
`KHIOPS_DRIVERS_LOCATION` can be set at post-install, including for Conda, via the `post-link.sh` script on Linux and `post-link.bat` on Windows.

**Comment by popescu-v** [comment]
We still need to tackle the "conda-based" environments like Colab where `$CONDA_PREFIX` is not defined: should we say that this is computed just as ` dirname $(dirname $(which khiops-env))` (assuming that `khiops-env` is in the right `bin` directory)?

In this case (if we make sure `khiops-env` is installed in the correct `bin` directory), we could make do without `$CONDA_PREFIX` in all Conda-like (Conda, Conda-based) environments, couldn't we?
