### ISSUE TITLE
Switch to an open source version of Java

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops#298]
#### Description
Java est désormais sous licence.
De nombreux utilisateurs ne vont plus utiliser la version Oracle de Java, et vont passer à une version open source, comme Eclipse Temurin JRE qui est compatible.
Il faudrait revoir le packaging de Khiops pour se baser préférentiellement sur cette version Open Source

#### Questions/Ideas
Je viens de faire un essai rapide en installant le JRE Temurin sur mon poste et en modifiant en dur le khiops.cmd, avec la ligne suivante juste après l'appel à khiops_env:
~~~
set KHIOPS_JAVA_PATH=C:\Program Files\Eclipse Adoptium\jre-21.0.1.12-hotspot\bin\server
~~~
Cela semble marcher correctement.

A faire pour une prise en compte complète:
- revoir l'installeur Khiops Windows pour installer par défaut Eclipse Temurin JRE
  - adapter le khiops_env.cmd pour rechercher dans la base de registre préférentiellement la version Temurin, sinon la version Oracle
- adapter aux environnements linux: ok, car on utilise Open JDK
- pas de problème pour Mac, car pas de Gui java actuellement

Remarque: 
- il existe une autre distribution de java, justj for all OSes:  https://eclipse.dev/justj/?page=documentation
- download: https://download.eclipse.org/justj/jres/11/downloads/latest/
- à évaluer: licence et impacts techniques https://github.com/merks/justj/blob/master/LICENSE

### Context
- Khiops version: 10.2

**Comment by marcboulle** [comment]
Pensez à prendre en compte le JDK pour produire le norm.jar depuis un poste Windows si on doit recompiler la esclasse java de NormGUI.

Attention à la version pour produire un byte code java compatible avec les distributions java sur toutes les plateformes cibles
- cf CMakeLists.txt, BUILD_JARS
  _Note: For final builds we recommend to use java 1.8 to ensure that the jar is compatible with all posterior java_
  _versions (from # 1.8 to the most recent ones)._

**Comment by bruno-at-orange** [comment]
close with #309
