### ISSUE TITLE
Should the Detect file format accept header line with empty or numeric fields ?

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops#299]
#### Description
On trouve parfois des fichiers de données avec des lignes d'entête atypiques:
- noms de champs avec uniquement caractères numériques (cf. fichier joint)
- nom de champ vide (ex: export de panda pour l'id des enregistrements)

Dans ce cas, la détection de format automatique ne détecte pas de ligne d'entête.

#### Questions/Ideas
- Dans le cas d'un champ vide, cela semble normal: un nom de champ valide ne peut être vide
- Dans le cas d'un nom de champ numérique, il est possible d'avoir une telle ligne d'entête, pourvu que deux colonnes différentes aient des noms différents
  - l'algorithme de détection de format utilise en fait une heuristique
    - aucun champ vide,
    - tous les noms doivent être différents
    - chaque champ doit comporter au moins un caractère alphabétique
  - cela marche très bien dans la plupart des cas
  - cela peut manquer certains cas atypiques (cf. fichier joint), mais cela évite de nombreux faux-positifs
    - sinon, chaque fichier dont la première ligne aurait des valeurs toutes distinctes serait systématiquement détecté comme ayant une ligne d'entete (même si toutes les valeurs sont numeriques)

Mon avis: l'heuristique actuelle me semble donner de bons résultats la plupart du temps, et il n'est pas nécessaire de la faire évoluer.

### Context
- Khiops version: 10.2

**Comment by alexisbondu** [comment]
Comment bien documenter ce "detect file format" pour ne pas surprendre l'utilisateur ? dans la guide de référence, et plus haut dans python. prévenir que cela ne peut pas être parfait .. c'est une heuristique. il doit y avoir au moins un caractère alphabétique par champ pour être éligible en une ligne d'entête + toutes les valeurs doivent être distinctes.

**Comment by marcboulle** [comment]
Mise a jour dans la section 2.1.1 du KhiopsGuide:
- Detect file format: heuristic help that scans the first few lines to guess the file format. The header line and field separator are updated on success, with a warning or an error in the log window only if necessary. _Note that the heuristic may fail in some cases: for example, a header line is only detected if all labels in the first line are distinct and contain at least one alphabetical character._

**Comment by marcboulle** [comment]
Fermeture avec la mise a jour du KhiopsGuide
