### ISSUE TITLE
Use targets in cmake to speed up the build process 

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#3]
We can specify the targets to be build:
```bash
cmake --build . --target target1 target2
```
It will speed up the build process (especially for unit test)

**Comment by folmos-at-orange** [comment]
I think we could also eliminate a number of flags: `LEARNING`, `PARALLEL`, `TESTING` . Your thoughts ?

**Comment by bruno-at-orange** [comment]
> I think we could also eliminate a number of flags: `LEARNING`, `PARALLEL`, `TESTING` . Your thoughts ?

yes indeed
