### ISSUE TITLE
Release 10.2.2

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#322]
- **Preparation**
  - [x] Update the `README.txt` and `WHATSNEW.txt` in the `packaging/common/khiops` directory
  - [x] Update the [PDF documentation][pdf-docs]
  - [x] Update the technical repo [khiops-win-install-assets][win-install-assets]
    - Update the versions of all assets that require an update, namely:
      - Khiops Visualization
      - Khiops Covisualization
      - Khiops PDF Docs
      - Java JRE installer
      - MS MPI installer
- **Full Test Loop**
  - [x] Create a pre-release tag in the `dev` or `*-hotfix` branch. The tag may be alpha, beta or
  release candidate, see [Versioning][versioning].
    - This will create a pre-release entry in the [release section][khiops-releases] with all the
    the CICD generated packages
  - [x] Create a pre-release tag in the `dev` or `*-hotfix` branch of the `khiops-python` repository
    - The will upload to a test channel the conda packages for Khiops
    - Example: `git tag 10.2.1-a1 dev`, then `git push --tags`
  - [x] Execute the end-to-end tests (aka. `LearningTest`) in all supported environments
    - If there are major issues, fix them (making issues, PRs) and go back to "Create a pre-release tag..."
  - [x] Execute the [manual tests for the GUI packages][manual-tests]

- **Finalize the Release**
  - [x] Update `src/Learning/KWUtils/KWKhiopsVersion.h` to the final release tag 10.2.2
  - [x] For a `MAJOR` or `MINOR` release: Merge `dev` into `main` (via PR)
      - `PATCH` releases are kept and tagged `*-hotfix` branch
  - [x] Create the final release tag (see also [Versioning][versioning]):
      - For a `MAJOR` or `MINOR` release: Tag the `main` branch (ex. `git tag v10.3.0` then `git push --tags`)
      - For a `PATCH` release: Tag the corresponding `*-hotfix` (ex. `git tag 10.2.1` then `git push --tags`)
  - [x] Copy and paste the release notes from `packaging/common/khiops/WHATSNEW.txt` to in the new
        [github release entry][khiops-releases]
  - [x] Remove any packages that haven't been deemed to release
    - We create more package than we release for testing purposes
  - [x] Sign the Windows package and replace it in the release
  - [ ] Release enablers: `khiops-python`, `khiops-notebook`.
    - **At this point the update of the website is unblocked**

- **Final Git Manipulations**
  - Only for `MAJOR` or `MINOR` releases, update the main
  - [ ] Create branch `*-hotfix` branched from the tagged commit in `main`
  - [x] Make the `dev` branch point to `main`
    - Locally execute `git fetch`, then `git switch main`, `git switch dev` and `git reset --hard
    main`
    - In the repo's [branch protecting settings][branch-settings] remove temporarily "Require a pull
    request before merging"
    - Locally execute `git push`
    - Restore in the  [branch protecting settings][branch-settings] "Require a pull request before
    merging"

**Comment by lucaurelien** [comment]
Done
