### ISSUE TITLE
Issue in pre-commit action

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#353]
#### Description
The pre-commit action fails on [yamlfix](https://github.com/KhiopsML/khiops/actions/runs/10472011297/job/29000505745#step:4:58). It seems it comes from a cache issue that produces the final error "ModuleNotFoundError: No module named 'maison.schema'" in yamlfix.

In the commit 5fed3d16fb2827d073acc37c6caca510f086b9b3, I updated the versions of the actions without improvment. So I comment the yamlfix in the file  **.pre-commit-config.yaml**. The checks are OK and we can work, but the bug remains.

#### Questions/Ideas
- The [pre-commit](https://github.com/pre-commit/action/tree/v3.0.1/?tab=readme-ov-file) action is deprecated, it is recommended to use [pre-commit](https://pre-commit.com/) instead. 
 - Why not doing without action: it can't be so hard to reproduce the [local setting](https://github.com/KhiopsML/khiops/wiki/Setting-Up-the-Development-Environment#4-install-pre-commit-in-the-repository). And it protect us from bad surprises...

**Comment by folmos-at-orange** [comment]
1) `yamlfix` fixed the "maison" module error in its latest version `1.17.0`(it's from 2 weeks ago so it probably didn't exist when you tested). I tested and it works fine.
2) The maintainers of the `pre-commit` action say that is "maintainance-only" so the action is not deprecated and I think we can safely use it.

**Comment by folmos-at-orange** [comment]
`yamlfix` was updated in #366  for `dev` and in #367 for `dev-v10`. I think we can safely close this.
