### ISSUE TITLE
khiops command return error 1 without any message.

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#383]
#### Description
When using khiops version 10.2.2 on Linux laptop, the khiops command return error 1 without any message.

After analysis, khiops fails when the KHIOPS_PROC_NUMBER environment variable is set to the number of available cores (20 on the laptop).

Previous version of khiops (10.2.0) was running fine with the same variable/value.

#### Questions/Ideas
-  remove the **--quiet** option from mpiexec command line

### Context
- Khiops version 10.2.2

**Comment by lucaurelien** [comment]
#310
