### ISSUE TITLE
Add LearningTest lite to the repo

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops#39]
A first proposal is to add `LearningTest` in the `test` directory with:
```
├── cmd
│   ├── python
├── datasets
│   ├── Adult
│   ├── Iris
│   └── Mushroom
├── MTdatasets
│   └── SpliceJunction
├── TestCoclustering
│   ├── Standard
├── TestKhiops
      └── Standard
```
I'm not sure it is necessary to add all these data. I was using `LearningTest` to test packages. For this purpose `Iris.txt` is good enough. We have to decide what is the purpose of LearningTest in CI

**Comment by bruno-at-orange** [comment]
We need the python scripts in the Khiops repository for ci tests (mainly to compare results and references). But also on our local machines to run the full LearningTest. I'm not sure it is a good thing to put these scripts on the Khiops repository: 
- by default, the scripts execute the tests located relatively to its own directory 
- if we test an old release of Khiops, we must use an old version of the scripts 

Why not a separate github project just for the python scripts and a `pypi` package: it will be available everywhere ?

**Comment by marcboulle** [comment]
There may be several levels of tests:
- automatic basic test, for pushes: only one test with Iris, for both exe MODL and MODL_Coclustering
- automatic standard test, for pull requests: TestKhiops/Standard and TestCoclusteringStandard
- manual exhaustif test, with all LearningTest
  - can be used anytime by any developper for massive non regression tests
  - should be used for important pull requests
  - must be used before merging on main branch

One first question if where to store:
- code for performing tests (LearningTest/cmd and LearningTest/doc)
  - on a distinct repo?
- data for all datasets
- data for for test scripts only
- data for reference results

Remarks
- the volume for basic and standard test is low (some tens of Mb) and consistent with the storage on a public repo
- the volume for exhaustif test if very important, and should be store on an internal data store
  - datasets: ~5 GB
  - scripts: ~1 Gb (could be reduced if local datasets are externalized)
  - reference results: ~3 Gb
- the scripts and reference results must be versionned
- the time to perform exhaustive test is very important
  - several hours for all tests
  - between one and two day for all+complete tests

On last question is how to synchrornize the version of the Khiops repo and that of LearningTest
- the test scripts must be versioned
  - beware that one some rare "special" commit on the Khiops repo have an impact on the scripts
  - keep track of these "special commits" by using tags (including in the dev branch)?
  - use these tagsto synchornized with the LearningTest repos?
- the reference results should be versionned
  -   but they may slight vary whith the version
