### ISSUE TITLE
Missing Khiops build for Ubuntu 24.04.1 (Noble Numbat)

### ISSUE THREAD

**Issue by sgouache** [KhiopsML/khiops#394]
#### Description
No package for ubuntu noble (24.04.1 LTS)

#### Questions/Ideas
- just asking to rebuild official khiops with this platform added to the target list 

### Context
- while building khiops-notebook, the base image has been upgraded to the latest ubuntu LTS
- when trying to get khiops for the current OS, it fails miserably

**Comment by popescu-v** [comment]
The GitHub-side CI is in place for building the Ubuntu 24.04.1 (LTS) Khiops packages.
However, they need to be tested:
- via LearningTest
- manually (for the GUI part).

**Comment by popescu-v** [comment]
LearningTest support is implemented. Hence, closing for now, as manual testing is deferred to #427
