### ISSUE TITLE
Refactor finalization for Khiops V11

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops#45]
Corrections to repo:
- keep en of lines in all file during pre-commit
   - otherwise the Windows RC compiler does not work
- modify the Norm genere executable to be be resilient to blank space in '// ##" comments, added by the new format
  - otherwise, the genere executable does not work
- corrections of new compiler warnings

Refactor coclustering instances x variables: simplify code, especially for classes:
- KWDataGrid: extend Check methods
- KWDataGridManager: mutualize common code
- KWDataGridVNSOptimizer: idem
- CCVarPartDataGridPostOptimizer: idem

**Comment by folmos-at-orange** [comment]
The `.rc` file for `KhiopsNativeInterface` is in UTF16 and thus considered binary for git. I suggest recoding it in UTF8

**Comment by marcboulle** [comment]
Merge pull request https://github.com/KhiopsML/khiops/pull/68 from KhiopsML/45-refactor-finalization-for-khi…
