### ISSUE TITLE
Make update-copyright end with empty lines

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#48]
Without this the `.rc` files do not compile.

**Comment by marcboulle** [comment]
The CMakeLists.txt files should be updated by adding the related .rc at the end of the add_library list, in order to activate the Windows RC compiler, for the following projects: MODL, MODL_Coclustering, KhiopsNativeInterface.

**Comment by marcboulle** [comment]
Checked the CMakeLists.txt files: ok
