### ISSUE TITLE
Improve the clang-format and its management

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops#52]
Actuellement, l'option "ColumnLimit: 120" du fichier .clang-format rend le reformatage des fichiers instables et peu pertinent:
- les commentaires sont reformatés selon cette limite, de façon souvent particulièrement inadaptée
  - en particulier quand c'est du code qui est commenté
- jusqu'à une demi-douzaine de formatages sont parfois nécessaire pour arriver à stabilisation
- cela crée une nuisance importante au moment des commits, puisque les fichiers reformatés changent

Il faudrait:
- soit affiner les options, pour a minima exclure les commentaire du reformatage
- soit supprimer cette option qui introduit plus de nuisance que de valeur 
  - éventuellement, on peut utiliser le pre-commit pour signaler les lignes trop longue en tant que warning
  - c'est le développeur qui doit alors lui-même raccourcir ses lignes trop longues

Il faut également dans le wiki indiquer comment activer le reformatage automatique dans les IDE (notamment Visual C++)

**Comment by folmos-at-orange** [comment]
After investigating I found that there [is an issue of lack of idempotency](https://reviews.llvm.org/D138402) due to long lines comments with tabs. This can happen to us when comment code since we use tabs for indenting.

I reproduced the issue, and indeed it requires two or more times to fix.

I propose:
- To set `ReflowComments: false` (I tested it and it works)
- To try to set it back to `true` once the fix to the issue arrives which will be with clang 17.

**Comment by marcboulle** [comment]
That looks ok for me: I just have to add this options in the .clang-format file of my branch?

Otherwise, which extension should be installed in Visual C++?

**Comment by folmos-at-orange** [comment]
> That looks ok for me: I just have to add this options in the .clang-format file of my branch?

I will fix this and add the fix to `dev`, you can then add it yourself to `dev-v11` (usually we should rebase, but this double dev setup makes it more difficult for begginners)

> Otherwise, which extension should be installed in Visual C++?

In visual studio 2022 is integrated: see https://learn.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-c-cpp-formatting?view=vs-2022

**Comment by marcboulle** [comment]
La solution Visual C++ ne marche pas:
cf. https://stackoverflow.com/questions/72449679/how-to-apply-format-when-saving-in-visual-studio-2022

J'ai essayé la solution proposée en installant l'extension "Format document on Save" (pas la version 2022, qui ne marche pas)
Paramétrage de Visual C++ 2022:
- menu Extensions/Gérer les extensions
- rechercher (Ctrl fn E) "Format "`
- choisir "Format document on save" (pas ... for VS2022, qui ne marche pas)
- télécharger
- l'extension sera activée après avoir quitté puis relancé Visual C++ 2022
- cela marche et le format est automatiquement appliqué à chaque sauvegarde

A documenter dans le wiki

**Comment by folmos-at-orange** [comment]
Fixed in commit e95d1599.
