### ISSUE TITLE
Lex and Yac compilation does not work on Windows

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops#54]
J'ai essayé d'activer la compilation des fichiers Lex et Yac sous Windows
- cf. fichiers CMakePresets.json, CMakeLists.txt, src\Learning\KWData\CMakeLists.txt

Cela ne marche pas.
- corriger le problème
- documenter sur le wiki
  - comment installer correctement les compilateur Lex et Yac sous Windows
  - comment activer la compilation Lex et Yac depuis Visual C++ 2022

**Comment by marcboulle** [comment]
Met le dans le path (FO)

**Comment by bruno-at-orange** [comment]
une vieille note :

Sur Windows, ça ne fonctionne pas avec [gow](https://github.com/bmatzelle/gow), il y a une [erreur non corrigée depuis 2014](https://github.com/bmatzelle/gow/issues/149), il faut utiliser [WinFlexBison](https://github.com/lexxmark/winflexbison/):

télécharger le zip et ajouter le repertoire dans le PATH

 il ya plusieurs problèmes :

tout fonctionne avec la version 2.5.24 mais il y a un bug avec la version 2.5.25
si gow est installé cmake prend la version de gow (quel que soit l'ordre des chemins dans le PATH). Il faut donc désinstaller gow (et utiliser [Git Bash](https://gitforwindows.org/) ?)

**Comment by marcboulle** [comment]
Essayé, sans succès:
- mettre les binaires de lex et yac dans le path (cmake les trouve, mais toujours des erreurs incompréhensible)
- supprimé gow
- utilisation des versions 2.5.24 ou 2.5.25 de flex et bison
- installation via Chocolatey
