### ISSUE TITLE
Optimize performance for release binaries with Visual C++ 2022

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops#58]
Les performances se sont fortement dégradées depuis le passage à Visual C++ 2022, d'un facteur 3 à 4.
Le paramétrage des options de compilation via CMake doit être optimisé.

Exemples sur ma machine avec la version V10.4.6i:
- LearningTest\TestKhiops\Standard\Adult
  - Data preparation time: 0:00:00.30 -> 0:00:01.05
  - SNB train time: 0:00:00.68 -> 0:00:02.26
  - Model deployment time: 0:00:00.09 ->0:00:00.38
- LearningTest\TestKhiops\Classification\ForestType
  - Data preparation time: 0:00:04.45 -> 0:00:17.79
  - SNB train time: 0:01:40.30 -> 0:05:28.17
  - Model deployment time: 0:00:00.18 -> 0:00:00.95

**Comment by marcboulle** [comment]
UPDATE IMPORTANT
Suite au problème sur ma machine avec Visual C++ 2022, on a mis en place une correction dans CMakePresets.json (commit "Fix cmake error for Visual C++ 2022" avec paramétrage explicite "generator": "Visual Studio 17 2022").
Les performances ont été calculées avec ce paramétrage

Comme ma machine s'est remise en marche miraculeusement, je viens d'annuler ce paramétrage du generator dans le CMakePresets.json.

Les nouvelles mesures de perfomance sont:
-  LearningTest\TestKhiops\Standard\Adult
     -  Data preparation time: 0:00:00.30 -> 0:00:00.32
     -  SNB train time: 0:00:00.68 -> 0:00:00.71
     -  Model deployment time: 0:00:00.09 ->0:00:00.10
 - LearningTest\TestKhiops\Classification\ForestType
    - Data preparation time: 0:00:04.45 -> 0:00:04.52
    - SNB train time: 0:01:40.30 -> 0:01.40.33
    - Model deployment time: 0:00:00.18 -> 0:00:00.20

Il n'y donc pas de dégradation de performance.
Et l'utilisation du générateur ninja est plus fluide et efficace avec l'IDE Visual C++ 2022.

A confirmer, et si OK, supprimer le paramétrage du generator dans CMakePresets.json

**Comment by marcboulle** [comment]
# Trace de mon problème de configuration avec Visual C++ 2022
Problème observé: l'IDE ne trouve plus cmake ni cl dans le path

>  [CMake] -- The CXX compiler identification is unknown
>  [CMake]   The CMAKE_CXX_COMPILER cl is not a full path and was not found in the PATH.
>  [CMake]   Tell CMake where to find the compiler by setting either the environment
>  [CMake]   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path

# Tentatives de correction
Etat initial
- outil Visual C++ 22 fraichement réinstallé
- machine rebooté après mises a jour
- pas de variable d'environnement
  
Essai 1
- lancement initial
- erreur de CMake: cl is not a full path and was not found in the PATH 
> [CMake] -- The CXX compiler identification is unknown
> [CMake] CMake Error at D:\Users\Public\Documents\DevGit\khiops\CMakeLists.txt:10 (project):
> [CMake]   The CMAKE_CXX_COMPILER:
> [CMake] 
> [CMake]     cl
> [CMake] 
> [CMake]   is not a full path and was not found in the PATH.
> [CMake] 
> [CMake]   Tell CMake where to find the compiler by setting either the environment
> [CMake]   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path

Essai 2
- suppression des répertoire .vs et build du projet git
- même erreur
  
Essai 3: 
- modification de l'installation
  - relancer l'installeur, avec option "Modifier"
  - ajouter "Prise en charge de C++\CLI pour Build Tools"
  - nécessite de redémarrer
- même erreur
  
Essai 4: 
- modification de l'installation
  - relancer l'installeur, avec option "Réparer"
  - nécessite de redémarrer
  - ça prend beaucoup de temps pour "Nous préparons tout pour vous. Cette opération peut prendre quelques minutes"
- même erreur

Essai 5:
- Dans Visual C++, "Supprimer le cache et reconfigurer"
- même erreur

Essai 6
- ajout de la ligne "generator": "Visual Studio 17 2022" 
    
Essai 7
- rechercher google de l'erreur "cl is not a full path and was not found in the PATH"
- ajout du path de cl.exe dans la variable d'environnement path
> "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64"
- nouveau type d'erreur de CMake
> Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
> Erreur		CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:60 (message):
> The C++ compiler
    "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe"
> is not able to compile a simple test program.
> It fails with the following output:
>   ...
>   ninja: build stopped: subcommand failed.

Essai 8
- rechercher google de l'erreur "cl is not a full path and was not found in the PATH"
  - https://stackoverflow.com/questions/35869564/cmake-on-windows
  - https://stackoverflow.com/questions/4101456/running-cmake-on-windows
  - https://discourse.cmake.org/t/using-visual-studio-2022-generators-install-target/8335
- correction: au dessous de la ligne 52 du CMakePresets.json de la ligne "generator": "Visual Studio 17 2022"

Correction avec Merge pull request #57 from KhiopsML/56-cmake-does-not-work-any-more-

# Tentatives de correction - suite
La solution précédente permet de compiler, mais l'environnement C++ n'est pas correctement configurer

Solution: 
- lancer un script de configuration de Visual C++ 2022 avant de lancer l'outil Visual Studio
- automatisé dans le fichier de commande suivant StartVisualCpp2022.cmd, que l'on peut mettre sur le bureau Windows
> @echo off
> set local
> REM Start Visual C++ 2022 after setting the compile env for x64
> REM Work around to solve CMake problem, taht does not configure compilation options properly
> 
> REM Call Visual C++ comand file to set the env variable for C++ x64 compiler
> call "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvars64.bat"
> 
> REM Start Visual C++ 
> call "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe"
> 
> exit 0
> endlocal

# Correction - épilogue
Trois jours après un update Windows de mon PC et de nombreux reboot, le comportement du PC s'est amélioré
- suite à l'update, le refresh (actualisation) depuis FileExplorer était nécessaire systématiquement après chaque création/supression/renommage de fichier
- trois jours après l'update, cela s'est remis à marcher normalement
  - est-ce une "policy" du SI qui a changé???
- j'ai réessayé de lancer Visual C++ 2022
  - sans la solution de contournement avec la commande StartVisualCpp2022.cmd
  - sans la correction du Merge pull request #57, en spécifiant la cible "generator": "Visual Studio 17 2022" dans le fichier CMakePresets.json
**Cela remarche!!!**

En annulant la correction dans CMakePresets.json, avec suppresion de la ligne "generator": "Visual Studio 17 2022", **les performance des exécutables sont à nouveau de qualité**. 

# Bilan
Plusieurs jour de perdu suite à un update de Windows sur ma machine
Une solution de contournement permettant de continuer à travailler, en attendant le rétablissement d'un comportement normal.

**Comment by folmos-at-orange** [comment]
The solution to implement is to set "Ninja" as the default generator for windows in `CMakePresets.json`

**Comment by folmos-at-orange** [comment]
For the record: I tested the Ninja generator in MacOS and the binaries it generates are not significantly faster
