### ISSUE TITLE
Eliminate or reduce data files from repository

### ISSUE THREAD

**Issue by felipe-olmos-orange** [KhiopsML/Khiops#7]
Currently there still are data files in the repo. There are two types:

- Those that will be moved to a "filer" hosting (TBD) : samples, docs
- Those that will be reduced: data files for C++ libraries samples (Learning)

After this operation we should reset the repo to efectively reduce its data usage: https://stackoverflow.com/a/26000395.

We should also see if we can get rid of  Git LFS after this operation.

**Comment by bruno-at-orange** [comment]
What about  LearningTest/Standard? It is used  on the old packaging project to validate the rpm/deb packages. We must run at least the adult test on each distro to validate the packages.

**Comment by felipe-olmos-orange** [comment]
Also, `LearningTest` is not in this version of the repo, maybe we should add it ?

**Comment by bruno-at-orange** [comment]
I don't know... what about the python scripts with a double location. Perhaps we wait the last version of Khiops

**Comment by felipe-olmos-orange** [comment]
Now that we are going the minify the "Standard" tests I think the way to go is the following:
- The code for the testing suite should go in this repository
- The Standard test suites should go in this repository
- The rest of the tests and datasets should go either in another repository or in another storage facility

**Comment by bruno-at-orange** [comment]
If we put the code for the test in this repo, we have to produce a package (pypi or conda). This package will be used in LearningTest.
