### ISSUE TITLE
KNI missing KNIGetFullVersion

### ISSUE THREAD

**Issue by sgouache** [KhiopsML/khiops#89]
#### Description
After installation of version 10.1.1 of KNI from [khiops.com](https://www.khiops.com/api/binaries/release/10.1.1/ubuntu/jammy/kni_10.1.1-0+jammy_amd64.deb) on ubuntu jammy my app started crashing on KNIGetFullVersion

#### Questions/Ideas
I don't really need this function, since GetVersion is there.
What makes be believe this is a bug is the fact that the header file still shows the symbol, while it disappeared from the library.

### Context
- KNI v10.1.1
- Ubuntu jammy
- attached output from nm -gD /usr/lib/libKhiopsNativeInterface.so (listing symbols in library)
[nm.log](https://github.com/KhiopsML/khiops/files/12818129/nm.log)

**Comment by marcboulle** [comment]
Problème non reproduit. Pas possible a priori que cette fonction ait disparue de KNI.
Pas d'explication. Utilisation d'un machine d'intégration devenue instable?
