### ISSUE TITLE
Document KhiopsML repositories

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#98]
#### Description
The number of repositories is increasing and we need to index and document them. 

#### Questions/Ideas
- List all repositories of the KhiopsML organisation
- Classify them into classes
  - Main repos
  - Documentation repos
  - Technical repos
- Discuss whether some repos may be fused
- Make a wiki page in the development wiki.

**Comment by marcboulle** [comment]
Vérifier la pertinence des libellés décrivant chaque repo

**Comment by alexisbondu** [comment]
Fait en séance de réunion d'équipe.
