### ISSUE TITLE
khiops-env linux/mac script takes a long time to find libjvm

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops#99]
#### Description
The `khiops-env` script may take a long time to find `libjvm.so` in some environments. For example in a default conda environment with openjdk installed khiops-env takes 1 minute in my machine. This is because `JAVA_HOME` is set to the root of the conda installation and thus the `find` command explores *all* its sub-directories.

This is critical for the `khiops-python` + Khiops system wide installation as it relies on `khiops-env` to obtain the environment but Java will not be required in newer versions as the `batch` option is deprecated and it will be removed with Khiops 11.

#### Questions/Ideas
- Two options
  - Improve the search heuristic: search only in selected sub-directories of `JAVA_HOME`
  - Add an option to skip the `libjvm.so` lookup.

### Context
- Khiops 10.x
- Linux/Mac

**Comment by bruno-at-orange** [comment]
The **khiops-env** script need to be improved, the script is provided by `khiops-core `and the java configuration is provided by the `khiops` package. The  line `# JAVA_HOME automatic setting` is replaced by the definition of `JAVA_HOME` e.g. `JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/`.

```bash
# Java configuration
# JAVA_HOME automatic setting

if [[ -n $JAVA_HOME ]]; then
   KHIOPS_KHIOPS_CLASSPATH=/usr/share/khiops/norm.jar:/usr/share/khiops/khiops.jar
   KHIOPS_JAVA_PATH=$(find -L "$JAVA_HOME" -name libjvm.so | xargs dirname)
fi
```
If `JAVA_HOME` is already defined it will set the` KHIOPS_KHIOPS_CLASSPATH `with khiops.jar which is not installed.
I think the solution here is to set `KHIOPS_KHIOPS_CLASSPATH` and `KHIOPS_JAVA_PATH` only in the khiops postinstall (It will be embedded in the replace process).
